/*
 * This file is generated by jOOQ.
 */
package cryptoscrapper.model.jooq.tables.records;


import cryptoscrapper.model.jooq.tables.Coin;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CoinRecord extends UpdatableRecordImpl<CoinRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 1582640306;

    /**
     * Setter for <code>public.coin.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.coin.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.coin.symbol</code>.
     */
    public void setSymbol(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.coin.symbol</code>.
     */
    public String getSymbol() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.coin.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.coin.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Coin.COIN.ID;
    }

    @Override
    public Field<String> field2() {
        return Coin.COIN.SYMBOL;
    }

    @Override
    public Field<String> field3() {
        return Coin.COIN.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSymbol();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSymbol();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public CoinRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CoinRecord value2(String value) {
        setSymbol(value);
        return this;
    }

    @Override
    public CoinRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public CoinRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CoinRecord
     */
    public CoinRecord() {
        super(Coin.COIN);
    }

    /**
     * Create a detached, initialised CoinRecord
     */
    public CoinRecord(Integer id, String symbol, String name) {
        super(Coin.COIN);

        set(0, id);
        set(1, symbol);
        set(2, name);
    }
}
