/*
 * This file is generated by jOOQ.
 */
package cryptoscrapper.model.jooq;


import cryptoscrapper.model.jooq.tables.Coin;
import cryptoscrapper.model.jooq.tables.CoinDetails;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.coin</code>.
     */
    public final Coin COIN = Coin.COIN;

    /**
     * The table <code>public.coin_details</code>.
     */
    public final CoinDetails COIN_DETAILS = CoinDetails.COIN_DETAILS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.COIN_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Coin.COIN,
            CoinDetails.COIN_DETAILS);
    }
}
