/*
 * This file is generated by jOOQ.
 */
package cryptoscrapper.model.jooq;


import cryptoscrapper.model.jooq.tables.Coin;
import cryptoscrapper.model.jooq.tables.CoinDetails;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.coin</code>.
     */
    public static final Coin COIN = Coin.COIN;

    /**
     * The table <code>public.coin_details</code>.
     */
    public static final CoinDetails COIN_DETAILS = CoinDetails.COIN_DETAILS;
}
